on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/mkdocs.yml"
  pull_request:
    types: [opened]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/mkdocs.yml"
  issue_comment:
    types: [created]

name: mkdocs

jobs:
  check-deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy-status: ${{ steps.check.outputs.triggered }}
    steps:
      - name: Check for deploy trigger
        id: check
        if: github.event_name == 'pull_request' || github.event_name == 'issue_comment'
        uses: shanegenschaw/pull-request-comment-trigger@v2.1.0
        with:
          trigger: "/deploy"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  deploy:
    needs: check-deploy
    if: (github.event_name == 'push') || (needs.check-deploy.outputs.deploy-status == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13.4
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Install dependencies
        run: |
          pip install ".[docs]"
      - name: Build docs
        run: mkdocs gh-deploy --force
      - name: Notify Teams
        if: success() && github.event_name == 'push'
        run: |
          curl -L -H 'Content-Type: application/json' -d '{
            "title": "Documentation Updated",
            "actor": "${{ github.actor }}",
            "repository": "${{ github.repository }}",
            "commit_message": "${{ github.event.head_commit.message }}",
            "docs_url": "https://https://motivation-and-behaviour.github.io/sieve/",
            "commit_url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          }' ${{ secrets.TEAMS_WORKFLOW_URL }}
